{% set name = "django-organizations" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e720dca732b5cb83878b2ef987cff026ffab05aa7d8bab8c1ec4add3c0c41d57

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django >=1.8.0
    - typing >=3.6.4

test:
  imports:
    - organizations

about:
  home: https://github.com/bennylope/django-organizations
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Multi-user accounts for Django projects

extra:
  recipe-maintainers:
    - hadim
