{% set name = "django-organizations" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f1d9febaa6c9d169a0d48b0228245d2fae16df3a124219008712c62895cc328

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=1.8.0
    - typing >=3.6.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - organizations

about:
  home: https://github.com/bennylope/django-organizations
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Multi-user accounts for Django projects

extra:
  recipe-maintainers:
    - hadim
