{% set name = "django-organizations" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8a93e7105695502f8dd2f7b4038d5cf356d15fcf29089eebb068b3139948d5e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - django >=1.8.0
    - typing >=3.6.4

test:
  imports:
    - organizations

about:
  home: https://github.com/bennylope/django-organizations
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Multi-user accounts for Django projects

extra:
  recipe-maintainers:
    - hadim
